[[libdrm]]
arch = "aarch64"
git-tree-sha1 = "4e05e5352d21849a3ce6dfbde25cf49d89da4000"
libc = "glibc"
os = "linux"

    [[libdrm.download]]
    sha256 = "df82283ca69cc935acc6d2235cc53e450472f5c6108b8b760299fd5fa8366446"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.aarch64-linux-gnu.tar.gz"
[[libdrm]]
arch = "aarch64"
git-tree-sha1 = "c69a08ccf27aeb9d3c4b1372bdf10afabdeee492"
libc = "musl"
os = "linux"

    [[libdrm.download]]
    sha256 = "dbb52ad1c510e362aac67a7f0c5c9868f1a8b6542918f28d726e601c2d18397d"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.aarch64-linux-musl.tar.gz"
[[libdrm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebae92517c95c23aa16e81fad2c22175ae6be947"
libc = "glibc"
os = "linux"

    [[libdrm.download]]
    sha256 = "fa7f98f9c1dbd9eea069952869d89772cb16fb641d32d0a5489b47cacaf18c71"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.armv7l-linux-gnueabihf.tar.gz"
[[libdrm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6b60ea13bc715568ff083f5f74e9091d7dad902"
libc = "musl"
os = "linux"

    [[libdrm.download]]
    sha256 = "6ba28846b58c35869ada27b48aebc0f66f266473ef87b036f55888bb8936be9d"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.armv7l-linux-musleabihf.tar.gz"
[[libdrm]]
arch = "i686"
git-tree-sha1 = "157065c9ef6ec30ba3ae3ae132a2d6b521791c93"
libc = "glibc"
os = "linux"

    [[libdrm.download]]
    sha256 = "1bd2b3f202bf5aed3cec6e870a3892cd4fea4dc7ba917b48ca9a356858bd7581"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.i686-linux-gnu.tar.gz"
[[libdrm]]
arch = "i686"
git-tree-sha1 = "95dd3e4df99ba2183c2cac6ca248891a6b1c16be"
libc = "musl"
os = "linux"

    [[libdrm.download]]
    sha256 = "081923f7701234a2d2f8567f0a04a41c23cdb165cb56183c82c182da3b7e230f"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.i686-linux-musl.tar.gz"
[[libdrm]]
arch = "powerpc64le"
git-tree-sha1 = "73158e6fc4617d2e41812ef61b2d30ec35cbca3b"
libc = "glibc"
os = "linux"

    [[libdrm.download]]
    sha256 = "18598da83f944cf4209d2dfb68ab5d892efa644b2e6809a4dc224037d135b109"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.powerpc64le-linux-gnu.tar.gz"
[[libdrm]]
arch = "x86_64"
git-tree-sha1 = "8d2ac2c40ffc146c7d7d6c463973c8a08543ba81"
libc = "glibc"
os = "linux"

    [[libdrm.download]]
    sha256 = "461e53c0d30386b9e221672a519ce37038d60b8542310909799560cac198d39d"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.x86_64-linux-gnu.tar.gz"
[[libdrm]]
arch = "x86_64"
git-tree-sha1 = "e55de5bdaea2a1de5123da1769803d83175954eb"
libc = "musl"
os = "linux"

    [[libdrm.download]]
    sha256 = "bd6717d6190dbff4adcc170867ae3cf91332b5febdad67cc49d6053b325e4e83"
    url = "https://github.com/JuliaBinaryWrappers/libdrm_jll.jl/releases/download/libdrm-v2.4.106+0/libdrm.v2.4.106.x86_64-linux-musl.tar.gz"
